#!/bin/sh

set -C -f
IFS="$(printf '%b_' '\n')"; IFS="${IFS%_}"

case "$(file --dereference --brief --mime-type -- "$1")" in
 text/* | */xml | application/json | application/x-ndjson) bat -p --theme ansi --terminal-width "$(($4-2))" -f "$1" ;;
esac
exit 1
