osd-bar=no
border=no
save-position-on-quit=yes
resume-playback=yes
screenshot-directory=~/Imagens/
screenshot-template="%F - %p"
script-opts=ytdl_hook-ytdl_path=yt-dlp
video-sync=display-resample
af=lavfi=[dynaudnorm=f=75:g=25:p=0.55]
