[env]
TERM = "xterm-256color"

[window]
dynamic_title = true
decorations = "None"
opacity = 0.99
padding = { x = 0, y = 0 }

[mouse]
hide_when_typing = false
bindings = [ { mouse = "Right", mods = "Control", action = "Paste" } ]

[keyboard]
bindings = [ { action = "CreateNewWindow", key = "N", mods = "Control | Shift" } ]

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "None"

# Font settings
[font]
glyph_offset = { x = 0, y = 0 }
size = 15.0
builtin_box_drawing = true

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

# Cursor settings
[cursor]
# style = "Underline"
unfocused_hollow = false

# Color settings
[colors]
draw_bold_text_with_bright_colors = false
transparent_background_colors = true

# Default colors
[colors.primary]
background = '#282828'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'
