[env]
TERM = "xterm-256color"

[window]
dynamic_title = true
decorations = "None"
opacity = 1.00
padding = { x = 0, y = 0 }

[mouse]
hide_when_typing = false
bindings = [ { mouse = "Right", mods = "Control", action = "Paste" } ]

[keyboard]
bindings = [ { action = "CreateNewWindow", key = "N", mods = "Control | Shift" } ]

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "None"

# Font settings
[font]
glyph_offset = { x = 0, y = 0 }
size = 15.0
builtin_box_drawing = true

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

# Cursor settings
[cursor]
style = "Underline"
unfocused_hollow = false

# Color settings
[colors]
draw_bold_text_with_bright_colors = false
transparent_background_colors = true

[colors.primary]
background = "#1c1e1f"
foreground = "#ffffff"

[colors.normal]
black = "#262626"
red = "#ee5396"
green = "#BE95FF"
yellow = "#42be65"
blue = "#78a9ff"
magenta = "#ff7eb6"
cyan = "#3ddbd9"
white = "#dde1e6"

[colors.bright]
black = "#393939"
red = "#ee5396"
green = "#BE95FF"
yellow = "#42be65"
blue = "#78a9ff"
magenta = "#ff7eb6"
cyan = "#3ddbd9"
white = "#dde1e6"
