[misc]
pre_sudo = true
set_title = false
assume_yes = true
no_retry = true
cleanup = true
notify_each_step = true
only = ["system", "firmware", "flatpak", "gnome_shell_extensions", "tldr"]
no_self_update = true
[post_commands]
"Arch Cleanup" = "sudo rm -rf /var/cache/pacman/ && paru -scc && paru -Rscn $(paru -Qqdt)"
[commands]
[linux]
arch_package_manager = "paru"
[flatpak]
use_sudo = false
